# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jwc-kefu

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ccr.ccs.tencentyun.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_4aeec56147ef4ca3b9bf2a982ca58a02 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2a277346453e4aba9aad83e1d82c0d40 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ccr.ccs.tencentyun.com/${{ secrets.AzureAppService_ContainerUsername_4aeec56147ef4ca3b9bf2a982ca58a02 }}/minijwc/kefu:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jwc-kefu'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_94854c6e76334bf8962dc0dec28e94fc }}
        images: 'ccr.ccs.tencentyun.com/${{ secrets.AzureAppService_ContainerUsername_4aeec56147ef4ca3b9bf2a982ca58a02 }}/minijwc/kefu:${{ github.sha }}'